### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tarcieri** [rust-secure-code/wg#1]
We need a logo!

**Comment by tarcieri** [comment]
<img width="815" alt="screen shot 2018-10-13 at 3 53 20 pm" src="https://user-images.githubusercontent.com/797/46910827-5f435d00-cf00-11e8-9bce-a045fca20b0b.png">

**Comment by joshlf** [comment]
> I love the idea of a Ferris wearing a ski mask while using a laptop like in all the corny hacker stock images but I don't think it's in line with message we want to get across.

I feel exactly the same way. On both counts, unfortunately.

**Comment by joshlf** [comment]
How about the Rust logo or Ferris on a padlock?

**Comment by stusmall** [comment]
![ferrislock](https://user-images.githubusercontent.com/1697444/46921669-827f1280-cfbb-11e8-848c-77c3a9d5b349.png)
A quick dirty lock ferris as a lock.  I'm no artist

**Comment by DrizztVD** [comment]
> 
> 
> ![ferrislock](https://user-images.githubusercontent.com/1697444/46921669-827f1280-cfbb-11e8-848c-77c3a9d5b349.png)
> A quick dirty lock ferris as a lock. I'm no artist

Thumbs up on that one.

**Comment by joshlf** [comment]
I tried a white-on-black Rust logo with the words "Secure Code" under it (like the [Embedded WG logo](https://raw.githubusercontent.com/rust-embedded/wg/master/assets/logo/ewg-logo-blue-white-on-transparent-256x256.png)), but I was just doing it in Mac Preview, so I couldn't get it the way I wanted, and I couldn't find a good font. I was looking for something old-school terminal-ish.

**Comment by tarcieri** [comment]
Here's the same thing sans ski mask:

![rust-secure-code2](https://user-images.githubusercontent.com/797/46922553-8ca31000-cfbf-11e8-9b90-31d9398f8c7d.png)

**Comment by Tom-Phinney** [comment]
Perhaps it should be animated, so that the ski mask disappears to the immediately-above image with just the old-fashioned key when one hovers over or clicks on the masked Ferris.

FYI, I'll probably participate in this WG as a lurker; my primary interest is in the potential crypto subgroup.

**Comment by Shnatsel** [comment]
How about a hermit Ferris? Quick sketch:

![hermit_ferris](https://user-images.githubusercontent.com/291257/46932562-f3c0d300-d058-11e8-8102-a5c589f83745.png)

**Comment by joshlf** [comment]
Wow I actually really love that.

**Comment by stusmall** [comment]
Same!

**Comment by joshlf** [comment]
@Shnatsel Would you be willing to run with that? Maybe add "Secure Code" on the shell?

**Comment by tarcieri** [comment]
I kind of know my way around Illustrator and would be happy to run with any particular concept, particularly if you're into having `.svg` and `.ai` versions of the logo

**Comment by joshlf** [comment]
I won't stop you :)

**Comment by Shnatsel** [comment]
Wow, glad to see you guys liked hermit Ferris!

In retrospect, I'd use the "gesturing" Ferris variant from http://www.rustacean.net/ and make him hold up the shell with one pincer, to make it look like he's doing something instead of just sitting there.

Putting text on the shell would require the logo to be quite large for the text to be readable. 100x100px is definitely out, and github userpics are even smaller. Also, since it does not incorporate the official Rust logo, I figure a mention of Rust is needed too. So I'd rather go for "Rust Secure Code Working Group" label nearby than on the shell itself.

Feel free to run with the idea. I have a pretty good grasp of Inkscape, so let me know if you run into some trouble with the vectors - perhaps I will be able to assist.

**Comment by tarcieri** [comment]
Okay, after much ado, may I present Hermes, the Hermetic Hermit Crab:

![hermes](https://user-images.githubusercontent.com/797/50059730-50b33500-013f-11e9-89df-4f3561b7c2d8.png)

I made him in Illustrator out of bits and pieces of Ferris. People seemed to like the hermit crab idea so I rolled with it, but I like metal so I tried giving him a metallic-colored shell.

I thought perhaps Ferris could use a friend or two...

**Comment by Shnatsel** [comment]
Instead of a shell I saw [a stack of stones](https://depositphotos.com/178467400/stock-photo-stacked-stones-on-white-background.html) for a moment and now I cannot unsee it.

I'll try to do my own take on the logo in vector form.

**Comment by tarcieri** [comment]
Here's an SVG and Illustrator version of "Hermes":

[Hermes.svg.gz](https://github.com/rust-secure-code/wg/files/2684041/Hermes.svg.gz)
[Hermes.ai.gz](https://github.com/rust-secure-code/wg/files/2684040/Hermes.ai.gz)

I can also try to do a bit more "natural" shell color...

**Comment by tarcieri** [comment]
Brown shell instead of gray:

![hermes brown shell](https://user-images.githubusercontent.com/797/50060050-780c0100-0143-11e9-8e25-6e45e40d0710.png)

**Comment by Tom-Phinney** [comment]
I'd still prefer Ferris to have some kind of black hat. Since Rust is more forward-looking than other languages, perhaps it should be a jaunty black beret.

**Comment by tarcieri** [comment]
@Shnatsel had suggested adding some gradients on the shell, so I thought I'd give that a try

![hermes brown shell](https://user-images.githubusercontent.com/797/50104652-75f78000-01df-11e9-900e-bfba56e22881.png)

**Comment by Shnatsel** [comment]
I've tried some shell designs with Ferris and this is what I've got. Presenting them in 64px size since that's how it will be most commonly presented (github/blog userpics, etc):

![screenshot from 2018-12-24 20 24 27](https://user-images.githubusercontent.com/291257/51078548-ccf55580-16b6-11e9-9401-4b05babe3232.png)

Then I tried messing around with the shell of the left and got these:

![screenshot from 2019-01-06 21 50 11](https://user-images.githubusercontent.com/291257/51078549-ccf55580-16b6-11e9-805e-f0bce6995f85.png)

**Comment by Tom-Phinney** [comment]
I prefer the last of the five above. Essentially, IMO simpler is better in terms of the shell (but I dislike the stacked ring version (top row right) intensely).

**Comment by Shnatsel** [comment]
Another day, another batch of shelled Ferrises:

![screenshot from 2019-01-13 22 56 35](https://user-images.githubusercontent.com/291257/51091140-9129c100-1786-11e9-8203-a8ca61e27f39.png)

I'm ready to proclaim the leftmost one my final proposal. Here's the source SVG:
[rustacean-shell2.2-spikes2.5-gradient2-shadow.svg.zip](https://github.com/rust-secure-code/wg/files/2753578/rustacean-shell2.2-spikes2.5-gradient2-shadow.svg.zip)

If we manage to agree on Hermes vs Ferris-in-Shell by tomorrow, we can publish the "Security as 2019 goal" under a logo.

**Comment by Shnatsel** [comment]
Hermes in 64px for comparison:
![screenshot from 2019-01-13 23 05 17](https://user-images.githubusercontent.com/291257/51091207-cb479280-1787-11e9-8ae2-35e41d7de90d.png)

**Comment by Tom-Phinney** [comment]
Of the five shelled Ferris candidates, I prefer the shell color of #3 (as it appears on my screen) but would be satisfied with #1. I don't like #5 or, to a lesser extent, #4. I don't like either Hermes logo; I think they look fierce, unlike friendly Ferris.

**Comment by tarcieri** [comment]
So this issue has been open for nearly 3 months at this point. Perhaps it's time to have a final call for logos and some sort of voting process for the winner.

I submitted a logo so I think it would be best if someone who didn't tried to organize some sort of vote for the winner. If people would like to do that over Twitter I can tweet it out, or there are any number of other ways we could do it (e.g. a new GitHub post which lists the contestants in random order and has people ❤️ them or what have you)

**Comment by Tom-Phinney** [comment]
Many people in the security community block Facebook and Twitter. Please choose a different website to conduct the poll.

**Comment by Shnatsel** [comment]
I can also crop and extend https://flic.kr/p/656T74 to make it square. It would also work pretty well for the likes of twitter or github userpics.

**Comment by joshlf** [comment]
OK, final call for submissions! I'll leave this up for 24h, and then open a poll. @Tom-Phinney I'll try to figure out a way to extend the poll beyond Twitter (probably to GitHub).

**Comment by Shnatsel** [comment]
FWIW I am on a business trip away from editing tools and will not be able to make a photo-based submission until the weekend. So disregard my "I can crop this" message above.

**Comment by Shnatsel** [comment]
For the photo to be square you will have to extend the background vertically with either liquid resize GIMP plugin or resynthesizer GIMP plugin. Nothing complicated, just gotta find and install one of these tools.

**Comment by tarcieri** [comment]
I am familiar with Photoshop's [content-aware resizing features](https://helpx.adobe.com/photoshop/using/content-aware-scaling.html) and can field that request 😉

**Comment by joshlf** [comment]
@tarcieri That'd be very helpful, thanks :)

**Comment by tarcieri** [comment]
Here's a square version resized with Photoshop's content aware scaling. Still seems a little weird, but I guess that's what you get out of these algorithms:

![hermitcrab](https://user-images.githubusercontent.com/797/52166773-7a5ff580-26c6-11e9-8985-0a78f00eae89.png)

**Comment by tarcieri** [comment]
Here it is after cropping the image first to make it a bit more square to begin with so the content-aware resize algorithm has less image to "fill in", which I think is what @Shnatsel was suggesting originally. Looks better to me:

![hermitcrab2](https://user-images.githubusercontent.com/797/52166850-65379680-26c7-11e9-9b01-b52ef5ea89c5.png)

**Comment by Shnatsel** [comment]
Photoshop also should have a clone of GIMP's Resynthesizer plugin, it should be called "Content aware _something_". You want the "Uncrop" operation from there. It should work better than liquid resize.

**Comment by Tom-Phinney** [comment]
For me the big question is: Do we want a logo that recognizably resembles Ferris, such as one of @Shnatsel's up-thread Ferris-under-a-shell images, or do we want a realistic photo like the above? My initial view was that a shelled Ferris was preferable from a marketing/publicity standpoint, but since security is a real-world problem maybe the above real image is more appropriate.

**Comment by tarcieri** [comment]
Here it is using Photoshop's Content-Aware Fill feature to fill in the gaps. Looks worse, IMO (more repetitive around the parts where it's filled in)

![hermitcrab3](https://user-images.githubusercontent.com/797/52167052-e2fca180-26c9-11e9-81fb-e136693e1b67.png)

**Comment by Shnatsel** [comment]
My final logo submission: 

![secure-code-wg-logo-final svg](https://user-images.githubusercontent.com/291257/53842772-b5449a00-3fa0-11e9-959b-78f61b058edf.png)

Archive with source SVG and oversized rendered PNG: [hermit-ferris-hires-vector.zip](https://github.com/rust-secure-code/wg/files/2933464/hermit-ferris-hires-vector.zip)

**Comment by joshlf** [comment]
Last call for submissions before we post the poll!

**Comment by joshlf** [comment]
(for real this time :P )

**Comment by tarcieri** [comment]
Final submission:

![hermes](https://user-images.githubusercontent.com/797/53845665-cbca0180-3f5e-11e9-8738-08e169077d14.png)

.ai, .svg, and .png in a .zip:

[hermes.zip](https://github.com/rust-secure-code/wg/files/2933645/hermes.zip)

**Comment by joshlf** [comment]
OK, time to vote!

- [Option 1](https://user-images.githubusercontent.com/291257/53842772-b5449a00-3fa0-11e9-959b-78f61b058edf.png)
- [Option 2](https://user-images.githubusercontent.com/797/50104652-75f78000-01df-11e9-900e-bfba56e22881.png)

Like this comment for Option 1, and heart for Option 2!

**Comment by felix91gr** [comment]
The aesthetics of Option 2 seem out of the common Rust's/Ferris' themes. I think Option 1 is so well received precisely because it fits so well within that frame.

**Comment by Tom-Phinney** [comment]
Agreed. Option 1 is Ferris in a protective hard shell. Option 2 is an aggressive/defensive Hermes, who looks like a relative of Ferris.

**Comment by tarcieri** [comment]
> Option 2 is an aggressive/defensive Hermes

As the artist, my intent was to make him smiling and look like he wants to give you a hug...

**Comment by joshlf** [comment]
> > Option 2 is an aggressive/defensive Hermes
>
> As the artist, my intent was to make him smiling and look like he wants to give you a hug...

Don't worry, @tarcieri , that's how it came off to me :)

**Comment by stusmall** [comment]
> > > Option 2 is an aggressive/defensive Hermes
> > 
> > 
> > As the artist, my intent was to make him smiling and look like he wants to give you a hug...
> 
> Don't worry, @tarcieri , that's how it came off to me :)

Same.  tbh I liked them both.  I'm glad we had two great options to pick from.

**Comment by DevQps** [comment]
I vote for Option 1!

**Comment by Shnatsel** [comment]
I've applied the closen logo to the Github organization.

@tarcieri could you apply it to the Twitter account as well? I don't think we have much presence elsewhere yet, so after that's done I'll close the issue.

**Comment by tarcieri** [comment]
@Shnatsel will do when I have a chance! (or I can share the password to the Twitter account)

**Comment by tarcieri** [comment]
I tried to add the logo but presently don't presently have access to the relevant 2FA device.

I think it'd be good if one other person in the WG had access to the account for just such an occasion (@Shnatsel ?)

**Comment by Shnatsel** [comment]
Works for me.

**Comment by tarcieri** [comment]
Okay, I'll ping you privately once I have access to the account again

**Comment by tarcieri** [comment]
Logo added to Twitter
