### ISSUE TITLE
Official Chat

### ISSUE THREAD

**Issue by tarcieri** [rust-secure-code/wg#2]
Zulip. IRC. Discord. Slack. Gitter. etc. There are lots of options. Where do we want to chat?

**Comment by joshlf** [comment]
Recapping discussions with people interested in this group, it seems that:
- Some people have strong feelings against Discord
- People are generally open to Zulip, although few feel strongly in favor

Speaking now from my own perspective, we want to make sure our communications are discoverable by others in the community, and is friendly to new users. IMO, this implies that we should place higher weight on one of the existing solutions that's already used by others in the community. This means Discord or Zulip (or maybe Gitter) get higher weight.

**Comment by tarcieri** [comment]
I've never used Zulip before but I'm willing to give it a go

**Comment by snf** [comment]
I used Zulip probably not long enough to find its limitations but I liked it

**Comment by joshlf** [comment]
OK, in that case, I propose Zulip. Let's leave this issue open for ~1 day to give folks time to voice disagreements, and then let's set up a stream?

**Comment by DrizztVD** [comment]
I used Zulip for a short while. I got the impression it has fewer problems than discord. I would like to try forging some applicable discussions on www.kialo.com, even if only to experiment, but that might be a pie in the sky.

**Comment by joshlf** [comment]
Alright, Zulip it is.
