### ISSUE TITLE
Guidelines on writing `unsafe` code

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-secure-code/wg#33]
While #19 focuses on reducing the amount of `unsafe` code in the ecosystem there are still many places where `unsafe` is required, and it should probably be a goal of this workgroup to make sure we have more "safe" `unsafe` code.

Are there any plans to produce a set of guidelines on writing `unsafe` code, or how to audit a crate containing `unsafe` code, to ensure it is logically sound?

**Comment by Shnatsel** [comment]
There is actually a separate WG for that: https://github.com/rust-lang/unsafe-code-guidelines

**Comment by Michael-F-Bryan** [comment]
Thanks @Shnatsel! I'll move this discussion over there.
