### ISSUE TITLE
Would this WG be interested in taking over the ownership of cargo-geiger?

### ISSUE THREAD

**Issue by anderejd** [rust-secure-code/wg#36]
Hi!

I'm currently the maintainer of the tool cargo-geiger. It seems like this working group is using the tool or at least recommending it for auditing dependencies. Would you be interested in taking over ownership and maintenance of the tool in question? I feel that my available open source time is not enough to take care of the tool on my own and write proper replies for each issue.

Best regards / anderejd

**Comment by tarcieri** [comment]
I think this would be a good home for it, although I'm fairly busy myself.

**Comment by anderejd** [comment]
That sounds fairly promising :) I've posted a related thread here to hopefully get some discussion going: https://github.com/anderejd/cargo-geiger/issues/87 Please feel free to chime in if you have the time.

**Comment by anderejd** [comment]
This issue is resolved: https://github.com/rust-secure-code/cargo-geiger/issues/87 🎉
