### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by stusmall** [rust-secure-code/wg#5]
I see no reason to not just take rust-lang and copy it.

https://github.com/rust-lang/rust/blob/master/CODE_OF_CONDUCT.md

We can replace the contact field with a link back to the members of the group.  Similar to how the embedded working group has done.  https://github.com/rust-embedded/wg/blob/master/CODE_OF_CONDUCT.md

Any objections?

**Comment by tarcieri** [comment]
Sounds good to me

**Comment by joshlf** [comment]
Sounds good to me too.

**Comment by alex** [comment]
+1 ship it

**Comment by stusmall** [comment]
It's up.  I'll update it to explicitly call out other communication channels as we add them.
